import Foundation

/// The answer to a permission request, and how it gets back to the agent.
///
/// Every other answer NotchPill gives is a *synthesised keystroke*: focus the
/// terminal, type `y`, press Return. That only works when the agent is a TUI in
/// a window we can focus, and it is guesswork — the keystroke goes wherever the
/// focus happens to be by the time it lands.
///
/// A `PreToolUse` hook can be answered properly. The hook process is still
/// running, blocked, waiting to print a verdict on stdout; all we have to do is
/// hand it one. So the channel is a file the hook is already watching for:
/// no focus stealing, no typing into anyone's window, and it works for agents
/// that have no terminal at all.
struct PermissionDecision: Equatable {
    enum Verdict: String, Equatable {
        case allow
        case deny
        /// Hand it back to the agent's own prompt. What a timeout means, and
        /// what anything unparseable is treated as — see `Verdict.init`.
        case ask
    }

    /// The request this answers. Generated by the hook, carried on the peek,
    /// and used as the decision file's name.
    var requestId: String
    var verdict: Verdict
    /// Shown to the agent when denying, so the model learns *why* rather than
    /// just that it was blocked.
    var reason: String?

    init(requestId: String, verdict: Verdict, reason: String? = nil) {
        self.requestId = requestId
        self.verdict = verdict
        self.reason = reason?.isEmpty == true ? nil : reason
    }

    /// Where the hook watches. One file per request, named by id, so two agents
    /// asking at once cannot read each other's answer.
    static func directory(home: URL = FileManager.default.homeDirectoryForCurrentUser) -> URL {
        home.appendingPathComponent(".notchpill/decisions", isDirectory: true)
    }

    /// Ids arrive from a hook payload, so they are not ours to trust: a `..`
    /// or a `/` in one would write the decision file outside the directory.
    /// Anything outside the safe set is dropped rather than escaped, which
    /// makes a hostile id produce a harmless name instead of a path.
    static func sanitize(_ id: String) -> String {
        let safe = id.unicodeScalars.filter {
            CharacterSet.alphanumerics.contains($0) || $0 == "-" || $0 == "_"
        }
        let name = String(String.UnicodeScalarView(safe))
        return name.isEmpty ? "unnamed" : String(name.prefix(64))
    }

    static func file(for requestId: String,
                     home: URL = FileManager.default.homeDirectoryForCurrentUser) -> URL {
        directory(home: home).appendingPathComponent("\(sanitize(requestId)).json")
    }

    var payload: [String: Any] {
        var out: [String: Any] = ["requestId": requestId, "verdict": verdict.rawValue]
        if let reason { out["reason"] = reason }
        return out
    }

    func encoded() throws -> Data {
        try JSONSerialization.data(withJSONObject: payload)
    }

    /// Writes the answer where the hook is watching.
    ///
    /// Written to a temporary name and moved into place, because the hook polls:
    /// a partially written file read mid-write would parse as no verdict at all,
    /// and the request would fall through to the agent's own prompt as though
    /// nobody had answered it.
    func write(home: URL = FileManager.default.homeDirectoryForCurrentUser) throws {
        let directory = Self.directory(home: home)
        PrivateStore.makeDirectory(directory)
        let final = Self.file(for: requestId, home: home)
        let staging = directory.appendingPathComponent(".\(UUID().uuidString).tmp")
        try encoded().write(to: staging)
        _ = try? FileManager.default.removeItem(at: final)
        try FileManager.default.moveItem(at: staging, to: final)
    }

    static func parse(_ data: Data) -> PermissionDecision? {
        guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let id = root["requestId"] as? String, !id.isEmpty,
              let raw = root["verdict"] as? String else { return nil }
        return PermissionDecision(requestId: id,
                                  verdict: Verdict(raw),
                                  reason: root["reason"] as? String)
    }

    /// A concise, bounded reason for returning a Claude plan. This goes only
    /// through the decision file to the blocked hook; it is never logged or
    /// synthesised as a keystroke into an arbitrary window.
    static func planRevisionReason(_ feedback: String) -> String? {
        let trimmed = feedback.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        return "Plan revision: " + String(trimmed.prefix(600))
    }
}

extension PermissionDecision.Verdict {
    /// Unknown text is `.ask`, never `.allow`.
    ///
    /// This is the one place where being wrong has a cost that is not symmetric:
    /// a garbled verdict read as "allow" runs a command nobody approved, while
    /// read as "ask" it costs one prompt the user was going to see anyway.
    init(_ raw: String) {
        switch raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
        case "allow", "yes", "y", "approve": self = .allow
        case "deny", "no", "n", "reject": self = .deny
        default: self = .ask
        }
    }

    /// What Claude Code expects back in `hookSpecificOutput.permissionDecision`.
    var hookValue: String { rawValue }
}
