import AppKit
import Combine

/// One remembered copy.
struct ClipboardEntry: Identifiable, Equatable {
    let id: UUID
    /// Trimmed for display; the full text is what gets copied back.
    let text: String
    let copiedAt: Date

    /// Enough to recognise the copy, not just its first few words.
    ///
    /// Runs of whitespace collapse to single spaces so an indented code block
    /// does not spend its first line on padding. Long enough to fill
    /// `displayLines` at its maximum; the row shrinks to fit whatever is
    /// shorter.
    var preview: String {
        let flat = text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
        let cap = Self.charsPerLine * Self.maxLines
        return flat.count <= cap ? flat : String(flat.prefix(cap - 1)) + "…"
    }

    /// Roughly how many characters fit on one line of the card at 10pt in its
    /// 340pt width. Approximate by nature — proportional text has no exact
    /// answer — and deliberately a little conservative, so the estimate errs
    /// towards reserving a line rather than clipping one.
    static let charsPerLine = 52
    /// Past four lines a single copy owns the whole card.
    static let maxLines = 4

    /// How many lines this entry actually needs.
    ///
    /// A one-word copy gets one line; a paragraph gets four. The view and the
    /// height budget both read this, because a card that draws more rows than
    /// it reserved pushes the deck's page dots off the bottom of the pill.
    var displayLines: Int {
        let needed = (preview.count + Self.charsPerLine - 1) / Self.charsPerLine
        return min(Self.maxLines, max(1, needed))
    }
}

/// Recent clipboard text, kept in memory only.
///
/// **Nothing here is written to disk.** A clipboard holds passwords, tokens and
/// private messages; persisting it would turn a convenience into a credential
/// file that outlives the session. History dies with the process, and the
/// feature is off until asked for.
///
/// Three kinds of copy are never recorded:
/// - items marked `org.nspasteboard.ConcealedType`, the convention password
///   managers use to say "do not remember this";
/// - items marked transient or autogenerated, which are machine chatter;
/// - anything `SecretRedactor` recognises as a key or token, because a value
///   worth redacting in a log is worth not storing at all.
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var entries: [ClipboardEntry] = []

    /// Deep enough to find the thing you copied a few steps ago, shallow
    /// enough that it is never a trove.
    private static let capacity = 12

    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Set while writing our own value back, so re-copying does not read as a
    /// new copy and reorder the list under the pointer.
    private var isEchoing = false

    private init() {}

    func start() {
        guard timer == nil else { return }
        // NSPasteboard has no change notification; polling changeCount is the
        // documented approach. 1s is below the threshold where a copy feels
        // unrecorded, and the check is an integer compare.
        let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        entries = []
    }

    /// Puts an entry back on the pasteboard.
    func copyBack(_ entry: ClipboardEntry) {
        isEchoing = true
        let board = NSPasteboard.general
        board.clearContents()
        board.setString(entry.text, forType: .string)
        lastChangeCount = board.changeCount
        isEchoing = false
    }

    func clear() { entries = [] }

    private func poll() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChangeCount else { return }
        lastChangeCount = board.changeCount
        guard !isEchoing else { return }

        let types = board.types ?? []
        let excluded: Set<NSPasteboard.PasteboardType> = [
            .init("org.nspasteboard.ConcealedType"),
            .init("org.nspasteboard.TransientType"),
            .init("org.nspasteboard.AutoGeneratedType"),
        ]
        guard excluded.isDisjoint(with: Set(types)) else { return }

        guard let text = board.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        // A value the log redactor would hide is a value not worth keeping.
        guard SecretRedactor.redact(trimmed) == trimmed else { return }

        record(trimmed)
    }

    private func record(_ text: String) {
        // Re-copying something already held moves it to the front rather than
        // storing it twice.
        var next = entries.filter { $0.text != text }
        next.insert(ClipboardEntry(id: UUID(), text: text, copiedAt: Date()), at: 0)
        entries = Array(next.prefix(Self.capacity))
    }
}
