import AppKit
import Combine

/// One remembered copy.
struct ClipboardEntry: Identifiable, Equatable {
    let id: UUID
    /// Trimmed for display; the full text is what gets copied back.
    let text: String
    let copiedAt: Date
    /// Kept regardless of how much has been copied since.
    var isPinned: Bool = false

    /// Enough to recognise the copy, not just its first few words.
    ///
    /// Runs of whitespace collapse to single spaces so an indented code block
    /// does not spend its first line on padding. Long enough to fill
    /// `displayLines` at its maximum; the row shrinks to fit whatever is
    /// shorter.
    var preview: String {
        let flat = text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
        let cap = Self.charsPerLine * Self.maxLines
        return flat.count <= cap ? flat : String(flat.prefix(cap - 1)) + "…"
    }

    /// Roughly how many characters fit on one line of the card at 10pt in its
    /// 340pt width. Approximate by nature — proportional text has no exact
    /// answer — and deliberately a little conservative, so the estimate errs
    /// towards reserving a line rather than clipping one -- more so since the
    /// pin column took a little width off the front of every row.
    static let charsPerLine = 50
    /// Past four lines a single copy owns the whole card.
    static let maxLines = 4

    /// How many lines this entry actually needs.
    ///
    /// A one-word copy gets one line; a paragraph gets four. The view and the
    /// height budget both read this, because a card that draws more rows than
    /// it reserved pushes the deck's page dots off the bottom of the pill.
    var displayLines: Int {
        let needed = (preview.count + Self.charsPerLine - 1) / Self.charsPerLine
        return min(Self.maxLines, max(1, needed))
    }

    /// What a copy *is*, when that can be told from the text alone: a colour
    /// gets its swatch, a link its mark, anything else is text. The row shows
    /// the object where it can rather than making you read the string to
    /// find out — a `#ff6a00` you recognise by eye before you have parsed it.
    enum Kind: Equatable {
        case color(red: Double, green: Double, blue: Double)
        case url
        case text
    }

    var kind: Kind { Self.kind(of: text) }

    static func kind(of text: String) -> Kind {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let rgb = hexColor(trimmed) { return rgb }
        if let url = URL(string: trimmed), let scheme = url.scheme?.lowercased(),
           ["http", "https"].contains(scheme), url.host != nil,
           !trimmed.contains(where: \.isWhitespace) {
            return .url
        }
        return .text
    }

    /// `#rgb`, `#rrggbb` or `#rrggbbaa`, with or without the hash. Nothing
    /// else — a bare six-digit number is far more often an id than a colour,
    /// so the hash or a hex letter has to be present.
    private static func hexColor(_ text: String) -> Kind? {
        var hex = text
        let hadHash = hex.hasPrefix("#")
        if hadHash { hex.removeFirst() }
        guard [3, 6, 8].contains(hex.count),
              hex.allSatisfy(\.isHexDigit),
              hadHash || hex.contains(where: { $0.isLetter })
        else { return nil }
        if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }
        let digits = Array(hex.prefix(6))
        func channel(_ i: Int) -> Double? {
            UInt8(String(digits[i..<i + 2]), radix: 16).map { Double($0) / 255 }
        }
        guard let r = channel(0), let g = channel(2), let b = channel(4) else { return nil }
        return .color(red: r, green: g, blue: b)
    }
}

/// Recent clipboard text, kept in memory only.
///
/// **Nothing here is written to disk.** A clipboard holds passwords, tokens and
/// private messages; persisting it would turn a convenience into a credential
/// file that outlives the session. History dies with the process, and the
/// feature is off until asked for.
///
/// Three kinds of copy are never recorded:
/// - items marked `org.nspasteboard.ConcealedType`, the convention password
///   managers use to say "do not remember this";
/// - items marked transient or autogenerated, which are machine chatter;
/// - anything `SecretRedactor` recognises as a key or token, because a value
///   worth redacting in a log is worth not storing at all.
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var entries: [ClipboardEntry] = []

    /// Deep enough to find the thing you copied a few steps ago, shallow
    /// enough that it is never a trove.
    private static let capacity = 12

    /// Pins are exempt from `capacity`, so they need a ceiling of their own --
    /// otherwise pinning is a way to grow the history without limit, which is
    /// the thing `capacity` exists to prevent.
    static let pinCapacity = 8

    /// The current search text. Empty means "show everything".
    @Published var query: String = ""

    /// True while the search field is open, which is not the same as having
    /// typed something: an open field with no query still owns the keyboard
    /// and still reserves a row in the card's height budget.
    @Published private(set) var isSearching = false

    /// What the card should draw: the history narrowed to the search.
    ///
    /// Matching runs over the full text rather than the preview, so a phrase
    /// past the truncation point still finds its entry.
    var visibleEntries: [ClipboardEntry] {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !needle.isEmpty else { return entries }
        return entries.filter { $0.text.localizedCaseInsensitiveContains(needle) }
    }

    var pinnedCount: Int { entries.lazy.filter(\.isPinned).count }

    func beginSearch() { isSearching = true }

    func endSearch() {
        isSearching = false
        query = ""
    }

    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Set while writing our own value back, so re-copying does not read as a
    /// new copy and reorder the list under the pointer.
    private var isEchoing = false

    private init() {}

    func start() {
        guard timer == nil else { return }
        // NSPasteboard has no change notification; polling changeCount is the
        // documented approach. 1s is below the threshold where a copy feels
        // unrecorded, and the check is an integer compare.
        let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        entries = []
        endSearch()
    }

    /// Puts an entry back on the pasteboard.
    func copyBack(_ entry: ClipboardEntry) {
        isEchoing = true
        let board = NSPasteboard.general
        board.clearContents()
        board.setString(entry.text, forType: .string)
        lastChangeCount = board.changeCount
        isEchoing = false
    }

    /// Forgets the unpinned history.
    ///
    /// Pins are the one part of this the person asked to keep, so the sweep
    /// leaves them; unpinning is how a pin goes away.
    func clear() { entries = entries.filter(\.isPinned) }

    /// Pins an entry, or unpins one already pinned.
    ///
    /// Silently does nothing when the pin ceiling is reached rather than
    /// evicting an older pin: dropping something the person deliberately kept
    /// in order to keep something else is the worse surprise of the two.
    func togglePin(_ entry: ClipboardEntry) {
        guard let index = entries.firstIndex(where: { $0.id == entry.id }) else { return }
        if entries[index].isPinned {
            entries[index].isPinned = false
        } else {
            guard pinnedCount < Self.pinCapacity else { return }
            entries[index].isPinned = true
        }
        entries = ordered(entries)
    }

    private func poll() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChangeCount else { return }
        lastChangeCount = board.changeCount
        guard !isEchoing else { return }

        let types = board.types ?? []
        let excluded: Set<NSPasteboard.PasteboardType> = [
            .init("org.nspasteboard.ConcealedType"),
            .init("org.nspasteboard.TransientType"),
            .init("org.nspasteboard.AutoGeneratedType"),
        ]
        guard excluded.isDisjoint(with: Set(types)) else { return }

        guard let text = board.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        // A value the log redactor would hide is a value not worth keeping.
        guard SecretRedactor.redact(trimmed) == trimmed else { return }

        record(trimmed)
    }

    /// Feeds an entry in without going through the pasteboard, so the store's
    /// ordering rules can be tested without touching the real clipboard.
    func recordForTesting(_ text: String) { record(text) }

    private func record(_ text: String) {
        // Re-copying something already held moves it to the front rather than
        // storing it twice, and keeps its pin: copying a pinned snippet again
        // is the most ordinary thing to do with one.
        let existing = entries.first { $0.text == text }
        var next = entries.filter { $0.text != text }
        next.insert(ClipboardEntry(id: existing?.id ?? UUID(), text: text,
                                   copiedAt: Date(),
                                   isPinned: existing?.isPinned ?? false), at: 0)
        entries = ordered(next)
    }

    /// Pins first, then the recent history trimmed to `capacity`.
    ///
    /// Only the unpinned tail is trimmed, which is what makes a pin a pin.
    private func ordered(_ list: [ClipboardEntry]) -> [ClipboardEntry] {
        let pinned = list.filter(\.isPinned)
        let rest = list.filter { !$0.isPinned }
        return pinned + rest.prefix(Self.capacity)
    }
}
